DB_SUCCESS = 0
DB_EXCEPTION = 1
DB_DATA_NOT_FOUND = 2
DB_ALREADY_EXISTING_DATA = 3
DB_UPDATING_FAILURE = 4
DB_DELETION_FAILURE = 5

ENDPOINT_SUCCESS = 10
ENDPOINT_EXCEPTION = 11
ENDPOINT_DATA_NOT_FOUND = 12
ENDPOINT_ALREADY_EXISTING_DATA = 13
ENDPOINT_UPDATING_FAILURE = 14
ENDPOINT_DELETION_FAILURE = 15
ENDPOINT_MOVE_TO_HISTORY_FAILURE = 16
ENDPOINT_INCORRECT_DATE = 17
ENDPOINT_INCORRECT_TIME = 18
